### PR TITLE
use YC600_MAX_NUMBER_OF_INVERTERS definition where suitable

### PR DESCRIPTION
**Pull request by fwolfst**

### CODE REVIEW

**Comment by patience4711** [comment]
how about adding sln like this<br>
strcpy(initCmd, strcat(sLen(initCmd), initCmd)); <br>
insteat of<br>
strcpy(initCmd, strncat(sLen(initCmd), initCmd, sizeof(sLen(initCmd)) + sizeof(initCmd)));

**Comment by fwolfst** [comment]
> how about adding sln like this strcpy(initCmd, strcat(sLen(initCmd), initCmd)); insteat of strcpy(initCmd, strncat(sLen(initCmd), initCmd, sizeof(sLen(initCmd)) + sizeof(initCmd)));

Thanks for looking at it. I had seen it, too. But you said that there are already some changes regarding appending the CRC. Waiting for the new code (so gar, there is only the .bin) before adding more changes to that area of the code.

**Comment by fwolfst** [comment]
(unrelated to this PR)

**Comment by patience4711** [comment]
uploaded the newest files, however the slen addition is not fully tested. In the sending of testcommands it works so i expect it to be good.<br>
I also changed the size of "bufferSend" and expect that "bufferSln" could be 6 or less

**Pull request closed without merging**
